---

rfb_shared_tool:
  DEFAULT_CHAN_NUM_MSG: 300
  DEFAULT_IPC_MSG_SIZE: 600
  DEFAULT_CHAN_TIMEOUT: 3

rfb_driver_db:
  DEFAULT_CRED_FILEPATH: '~/Battery-Experiments-Manager/devops/mn_manager/.cred.yaml'

#################### MN MANAGER ####################
rfb_mn_manager:
  DEFAULT_CRED_FILEPATH               : 'devops/mn_manager/.cred.yaml' #Max number of allowed message per chan
  DEFAULT_MN_NODE_NAME                : 'cu_manager_node'
  DEFAULT_NODE_PERIOD                 : 750 # ms # Period of the node
  DEFAULT_TIMEOUT_BETWEEN_CONNECTIONS : 15
  DEFAULT_DATA_SIZE                   : 900 # Max size of the data message