---
#YAML FILE START

__main__: "INFO"

##### DEV ######
rfb_mn_manager: "INFO"
rfb_driver_db: "INFO"

##### SYS #####
rfb_config_tool: "ERROR"
rfb_logger_tool: "ERROR"
rfb_shared_tool: "ERROR"

file_handlers: {}